services:
  agent:
    tty: true
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: agent
    restart: always
    env_file:
      - ../.env
    volumes:
      - ./data:/app/data
